export const Products = [
  {
    image: '/hero-pic-2.png',
    name: 'Snickers',
    price: '9.99$',
    category: 'shoes',
  },
  {
    image: '/hero-pic-1.png',
    name: 'Shirt',
    price: '5.99',
    category: 'shirts',
  },
  {
    image: '/hero-pic-2.png',
    name: 'Snickers',
    price: '9.99$',
    category: 'shoes',
  },
  {
    image: '/hero-pic-1.png',
    name: 'Shirt',
    price: '5.99',
    category: 'shirts',
  },
  {
    image: '/hero-pic-2.png',
    name: 'Snickers',
    price: '9.99$',
    category: 'shoes',
  },
  {
    image: '/hero-pic-1.png',
    name: 'Shirt',
    price: '5.99',
    category: 'shirts',
  },
  {
    image: '/hero-pic-2.png',
    name: 'Snickers',
    price: '9.99$',
    category: 'shoes',
  },
  {
    image: '/hero-pic-1.png',
    name: 'Shirt',
    price: '5.99',
    category: 'shirts',
  },
  {
    image: '/hero-pic-2.png',
    name: 'Snickers',
    price: '9.99$',
    category: 'shoes',
  },
  {
    image: '/hero-pic-1.png',
    name: 'Shirt',
    price: '5.99',
    category: 'shirts',
  },
  {
    image: '/hero-pic-2.png',
    name: 'Snickers',
    price: '9.99$',
    category: 'shoes',
  },
  {
    image: '/hero-pic-1.png',
    name: 'Shirt',
    price: '5.99',
    category: 'shirts',
  },
  {
    image: '/hero-pic-2.png',
    name: 'Snickers',
    price: '9.99$',
    category: 'shoes',
  },
  {
    image: '/hero-pic-1.png',
    name: 'Shirt',
    price: '5.99',
    category: 'shirts',
  },
  {
    image: '/hero-pic-2.png',
    name: 'Snickers',
    price: '9.99$',
    category: 'shoes',
  },
  {
    image: '/hero-pic-1.png',
    name: 'Shirt',
    price: '5.99',
    category: 'shirts',
  },
];